### ISSUE TITLE
Prevent new trains from spawning on occupied entry points

### ISSUE THREAD

**Issue by ksmonkey123** [WaDosCh/SimTrack#58] opened 2018-02-22 23:22 UTC
### Current Behaviour
Arbitrarily many trains can spawn "on top of each other" on a single spawn point.

### Requested Behaviour
No new trains should be spawned while the spawn point is occupied.

**Comment by ksmonkey123** [comment] 2018-02-22 23:25
@judos use `Model#isTileReserved(TileCoordinate)` to check if a tile is reserved

**Comment by judos** [comment] 2018-02-23 00:43
Fixed, but please note: It doesn't work if game is paused since trains won't reserve anything yet. So basically spawning more than 1 train per tick is unsafe.

**Comment by ksmonkey123** [comment] 2018-02-23 20:05
*This reopen is simply to remind us about the remaining issues. These can be solved as follows:*

 - The debug tools can simply call `model.getClock().pause()` and `model.getClock().resume()` for pause and resume functionality.
 - Trains can take the tick time from `model.getClock().getTickDuration()`. This will be `0` if the clock is paused and therefore stop trains from moving.
 - The spawner can also use `model.getClock().getTickDuration()` to determine the *game time* since the last train spawned.

**Comment by judos** [comment] 2018-02-24 01:53
The issue is definitely fixed with https://github.com/WaDosCh/SimTrack/commit/9c4c79c1902af9fec0f41b19485a918cd63bac07.
For the gameClock we can open a new ticket with the respective problems.

**Closed by judos** 2018-02-24 01:53 UTC
Labels: enhancement
